### PR TITLE
Refactor folder structure and building

### PR DESCRIPTION
**Pull request by Ymil**
Hiii

I hope this message finds you well.

I have a proposal for refactoring the project files to improve organization:

- Move all code to the src directory.
- Remove the compiled assets files to avoid duplication.
- Add a build script in the dist directory to create a distribution zip file.
- Update the github workflow, but i dont sure that it's ok.

Please let me know your thoughts on these changes.

Thank you for your consideration.

Best regards,

### CODE REVIEW

**Comment by antonlukin** [comment]
Hi @Ymil 
Thank you for your work! It seems that this approach is more convenient for deployment. But it is not yet very clear to me how to develop the plugin locally. If I specify the src/ folder as the project root, the plugin does not see the builded styles and scripts.

Can we work on this point? If so you can use [pr/5](https://github.com/antonlukin/social-planner/tree/pr/5) branch to sync your changes

image
image

**Comment by Ymil** [comment]
Hi @antonlukin.

True, this solution does not contain support for local development.

I have a proposal:
scss files are compiled when changes are made in `src` and go to `dist` using `gulp watch`, php files are placed in `dist` with a symbolic link, all this automatically with a bash script.

Is this ok?

Bye!

**Comment by Ymil** [comment]
HI @antonlukin 

I add change, you can try use `npm run build-dev` and create link symbolic from dist to plugin folder wordpress?

add steeps in the readme: https://github.com/antonlukin/social-planner/blob/13589a85e9862c59c3fcd65b7c5453f3d55d2b1b/README.md

**Comment by antonlukin** [comment]
Hi @Ymil
Muchas gracias for your work. Just one more note.
I use docker for a local development. For ex I use this part of docker-compose.yml config:
```
volumes:
      - "./options/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./options/php.ini:/usr/local/etc/php/php.ini"
      - "./wordpress:/var/www/html"
      - "../social-planner/dist/:/var/www/html/wp-content/plugins/social-planner"
      - "../sharing-image:/var/www/html/wp-content/plugins/sharing-image"
 ```
So docker can't see aliased folders from `../src` path. Of course i can redesign the docker file architecture but I want to understand your original goal. What is the idea behind the updated approach?
If you just want to create an archive before deploying, maybe it would be easier to use the `git archive -o social-planner.zip master` command? We already have a `.gitattributes` file inside the root folder. Or is the main task not to store assets files (js,css) in the repository, but only their sources?

In any case, I'm open to suggestions!

**Comment by Ymil** [comment]
Hi @antonlukin, i don't knowed this feature of git that's greats, thanks for this.

My propourse have two points.
- because it's that's more clear but really this have mores problems for use.
- The first time i edit the proyect i edited the compiled files, but this has a problem of layer eight.

Maybe we can reflected this propourse i have more jeje.
Later send emails for this.

Bye

**Pull request closed without merging**
